# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Base image with Python 3.13
FROM python:3.13-slim

# Set the working directory
WORKDIR /app

# Install hatchling and uv
RUN pip install hatchling uv

# Copy the project files
COPY . .

# Install the project dependencies
RUN uv sync --frozen --no-dev --no-editable

# Specify environment variables for OAuth if needed
# ENV GOOGLE_CLIENT_ID=your_client_id
# ENV GOOGLE_CLIENT_SECRET=your_client_secret

# Expose any necessary ports (if applicable)
# EXPOSE 4100

# Entry point to run the MCP server
ENTRYPOINT ["uv", "run", "mcp-gsuite"]

# Provide default command options (can be overridden when running the container)
CMD ["--gauth-file", "/path/to/.gauth.json", "--accounts-file", "/path/to/.accounts.json"]